import type { ComponentType } from "react";
import {
  Activity,
  Asterisk,
  AtSign,
  Boxes,
  Component,
  Eclipse,
  Sparkles,
  TextCursorInput,
} from "lucide-react";

import {
  AvatarCatalogPreview,
  ActionMenuPreview,
  AuroraPreview,
  ButtonCatalogPreview,
  GlowCardPreview,
  GlassCardPreview,
  GradientPreview,
  GridPreview,
  InteractiveHoverButtonPreview,
  MagneticPreview,
  MarqueePreview,
  NoisePreview,
  NumberTickerPreview,
  RainbowButtonPreview,
  RevealPreview,
  RippleButtonPreview,
  SegmentedControlPreview,
  ShineBorderPreview,
  ShimmerPreview,
  ShinyButtonPreview,
  SpotlightPreview,
  StarsPreview,
  StatusBadgePreview,
  TooltipCatalogPreview,
  TypingPreview,
} from "./previews";

export type CatalogKind =
  | "components"
  | "backgrounds"
  | "effects"
  | "animations"
  | "texts";

export type CatalogProduct = {
  kind: CatalogKind;
  label: string;
  singularLabel: string;
  description: string;
  basePath: `/${CatalogKind}`;
  icon: typeof Component;
};

export type CatalogItem = {
  slug: string;
  name: string;
  kind: CatalogKind;
  category: string;
  description: string;
  tags: string[];
  preview: ComponentType;
  sourceFile: string;
  registryName: string;
  dependencies: string[];
  code: string;
  sourceUrl: string;
  author: string;
  license: string;
  attribution?: string;
};

export const catalogProducts: CatalogProduct[] = [
  {
    kind: "components",
    label: "Components",
    singularLabel: "Component",
    description: "Accessible building blocks for product interfaces.",
    basePath: "/components",
    icon: Component,
  },
  {
    kind: "backgrounds",
    label: "Backgrounds",
    singularLabel: "Background",
    description: "Atmospheric surfaces for heroes, cards and sections.",
    basePath: "/backgrounds",
    icon: Eclipse,
  },
  {
    kind: "effects",
    label: "Effects",
    singularLabel: "Effect",
    description: "Focused hover, glow and pointer interactions.",
    basePath: "/effects",
    icon: Sparkles,
  },
  {
    kind: "animations",
    label: "Animations",
    singularLabel: "Animation",
    description: "Motion primitives that make interfaces feel alive.",
    basePath: "/animations",
    icon: Activity,
  },
  {
    kind: "texts",
    label: "Texts",
    singularLabel: "Text effect",
    description: "Expressive text treatments for product storytelling.",
    basePath: "/texts",
    icon: TextCursorInput,
  },
];

const sourceLinks = {
  magic: "https://magicui.design/docs/components",
  reui: "https://reui.io/components",
  layouts: "https://www.ui-layouts.com/components/buttons",
  triple: "https://ui.tripled.work/components",
  animate: "https://animate-ui.com/docs/components/backgrounds/stars",
  smooth: "https://smoothui.dev/docs/components/dropdown-menu",
} as const;

const baseDependencies = ["@base-ui/react", "lodash"];

export const catalogItems: CatalogItem[] = [
  {
    slug: "avatar",
    name: "Avatar",
    kind: "components",
    category: "Identity",
    description: "Composable identity primitives for people, teams and presence.",
    tags: ["identity", "base-ui", "profile"],
    preview: AvatarCatalogPreview,
    sourceFile: "src/components/shomaui/avatar.tsx",
    registryName: "avatar",
    dependencies: baseDependencies,
    code: `import { Avatar, AvatarFallback } from "@/components/shomaui/avatar";\n\n<Avatar><AvatarFallback>SK</AvatarFallback></Avatar>`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "button",
    name: "Button",
    kind: "components",
    category: "Actions",
    description: "Base UI powered actions with accessible states and sizes.",
    tags: ["actions", "base-ui", "forms"],
    preview: ButtonCatalogPreview,
    sourceFile: "src/components/shomaui/button.tsx",
    registryName: "button",
    dependencies: [...baseDependencies, "class-variance-authority"],
    code: `import { Button } from "@/components/shomaui/button";\n\n<Button>Continue</Button>`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    kind: "components",
    category: "Disclosure",
    description: "Keyboard-friendly contextual help built on Base UI primitives.",
    tags: ["disclosure", "base-ui", "feedback"],
    preview: TooltipCatalogPreview,
    sourceFile: "src/components/shomaui/tooltip.tsx",
    registryName: "tooltip",
    dependencies: baseDependencies,
    code: `import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/shomaui/tooltip";\n\n<Tooltip>...</Tooltip>`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "action-menu",
    name: "Action Menu",
    kind: "components",
    category: "Navigation",
    description: "Compact actions menu with shortcuts and destructive states.",
    tags: ["menu", "dropdown", "base-ui"],
    preview: ActionMenuPreview,
    sourceFile: "src/components/shomaui/components/action-menu.tsx",
    registryName: "action-menu",
    dependencies: baseDependencies,
    code: `import { ActionMenu } from "@/components/shomaui/components/action-menu";\n\n<ActionMenu label="Actions" />`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "glass-card",
    name: "Glass Card",
    kind: "components",
    category: "Surfaces",
    description: "Layered glass surface for dashboards and product highlights.",
    tags: ["card", "glass", "surface"],
    preview: GlassCardPreview,
    sourceFile: "src/components/shomaui/components/glass-card.tsx",
    registryName: "glass-card",
    dependencies: ["lodash"],
    code: `import { GlassCard } from "@/components/shomaui/components/glass-card";\n\n<GlassCard glow>...</GlassCard>`,
    sourceUrl: sourceLinks.triple,
    author: "ShomaUI + UI-TripleD references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "status-badge",
    name: "Status Badge",
    kind: "components",
    category: "Feedback",
    description: "Consistent new, stable, beta and deprecated statuses.",
    tags: ["badge", "status", "feedback"],
    preview: StatusBadgePreview,
    sourceFile: "src/components/shomaui/components/status-badge.tsx",
    registryName: "status-badge",
    dependencies: ["@base-ui/react", "lodash"],
    code: `import { StatusBadge } from "@/components/shomaui/components/status-badge";\n\n<StatusBadge status="stable" />`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "segmented-control",
    name: "Segmented Control",
    kind: "components",
    category: "Navigation",
    description: "Base UI tab behavior presented as a compact segmented switcher.",
    tags: ["tabs", "navigation", "base-ui"],
    preview: SegmentedControlPreview,
    sourceFile: "src/components/shomaui/components/segmented-control.tsx",
    registryName: "segmented-control",
    dependencies: [...baseDependencies],
    code: `import { SegmentedControl } from "@/components/shomaui/components/segmented-control";\n\n<SegmentedControl items={["Day", "Week", "Month"]} />`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "rainbow-button",
    name: "Rainbow Button",
    kind: "components",
    category: "Actions",
    description: "Animated gradient action button for high-emphasis moments.",
    tags: ["button", "gradient", "animated"],
    preview: RainbowButtonPreview,
    sourceFile: "src/components/shomaui/rainbow-button.tsx",
    registryName: "rainbow-button",
    dependencies: [...baseDependencies, "class-variance-authority"],
    code: `import RainbowButton from "@/components/shomaui/rainbow-button";\n\n<RainbowButton>Launch project</RainbowButton>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "ripple-button",
    name: "Ripple Button",
    kind: "components",
    category: "Actions",
    description: "Click-position ripple feedback for tactile actions.",
    tags: ["button", "ripple", "interaction"],
    preview: RippleButtonPreview,
    sourceFile: "src/components/shomaui/ripple-button.tsx",
    registryName: "ripple-button",
    dependencies: ["lodash"],
    code: `import RippleButton from "@/components/shomaui/ripple-button";\n\n<RippleButton>Click me</RippleButton>`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shiny-button",
    name: "Shiny Button",
    kind: "components",
    category: "Actions",
    description: "Motion-powered highlight sweep for premium calls to action.",
    tags: ["button", "motion", "shine"],
    preview: ShinyButtonPreview,
    sourceFile: "src/components/shomaui/shiny-button.tsx",
    registryName: "shiny-button",
    dependencies: ["lodash", "motion"],
    code: `import ShinyButton from "@/components/shomaui/shiny-button";\n\n<ShinyButton>Shiny action</ShinyButton>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "interactive-hover-button",
    name: "Interactive Hover Button",
    kind: "components",
    category: "Actions",
    description: "Arrow-reveal button interaction for compact navigation.",
    tags: ["button", "hover", "navigation"],
    preview: InteractiveHoverButtonPreview,
    sourceFile: "src/components/shomaui/interactive-hover-button.tsx",
    registryName: "interactive-hover-button",
    dependencies: ["lodash", "lucide-react"],
    code: `import InteractiveHoverButton from "@/components/shomaui/interactive-hover-button";\n\n<InteractiveHoverButton>View details</InteractiveHoverButton>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "stars",
    name: "Stars Background",
    kind: "backgrounds",
    category: "Space",
    description: "Deterministic animated star field inspired by Animate UI.",
    tags: ["stars", "space", "animated"],
    preview: StarsPreview,
    sourceFile: "src/components/shomaui/background/stars-background.tsx",
    registryName: "stars-background",
    dependencies: ["lodash"],
    code: `import StarsBackground from "@/components/shomaui/background/stars-background";\n\n<StarsBackground>...</StarsBackground>`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
    attribution: "Inspired by the Animate UI Stars Background concept.",
  },
  {
    slug: "grid",
    name: "Grid Background",
    kind: "backgrounds",
    category: "Patterns",
    description: "Responsive CSS grid surface for structured layouts.",
    tags: ["grid", "pattern", "css"],
    preview: GridPreview,
    sourceFile: "src/components/shomaui/background/grid-background.tsx",
    registryName: "grid-background",
    dependencies: ["lodash"],
    code: `import GridBackground from "@/components/shomaui/background/grid-background";\n\n<GridBackground />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "aurora",
    name: "Aurora Background",
    kind: "backgrounds",
    category: "Gradients",
    description: "Soft layered gradient light for hero and empty states.",
    tags: ["aurora", "gradient", "hero"],
    preview: AuroraPreview,
    sourceFile: "src/components/shomaui/background/aurora-background.tsx",
    registryName: "aurora-background",
    dependencies: ["lodash"],
    code: `import AuroraBackground from "@/components/shomaui/background/aurora-background";\n\n<AuroraBackground>...</AuroraBackground>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "noise",
    name: "Noise Background",
    kind: "backgrounds",
    category: "Texture",
    description: "Asset-free texture layer made from CSS gradients.",
    tags: ["noise", "texture", "css"],
    preview: NoisePreview,
    sourceFile: "src/components/shomaui/background/noise-background.tsx",
    registryName: "noise-background",
    dependencies: ["lodash"],
    code: `import NoiseBackground from "@/components/shomaui/background/noise-background";\n\n<NoiseBackground />`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "spotlight-card",
    name: "Spotlight Card",
    kind: "effects",
    category: "Pointer",
    description: "Pointer-aware radial light that keeps content readable.",
    tags: ["spotlight", "pointer", "card"],
    preview: SpotlightPreview,
    sourceFile: "src/components/shomaui/effects/spotlight-card.tsx",
    registryName: "spotlight-card",
    dependencies: ["lodash"],
    code: `import SpotlightCard from "@/components/shomaui/effects/spotlight-card";\n\n<SpotlightCard>...</SpotlightCard>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shine-border",
    name: "Shine Border",
    kind: "effects",
    category: "Borders",
    description: "Lightweight conic-gradient border animation.",
    tags: ["border", "shine", "css"],
    preview: ShineBorderPreview,
    sourceFile: "src/components/shomaui/effects/shine-border.tsx",
    registryName: "shine-border",
    dependencies: ["lodash"],
    code: `import ShineBorder from "@/components/shomaui/effects/shine-border";\n\n<ShineBorder>...</ShineBorder>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "magnetic",
    name: "Magnetic",
    kind: "effects",
    category: "Pointer",
    description: "Subtle pointer attraction wrapper for interactive targets.",
    tags: ["magnetic", "pointer", "interaction"],
    preview: MagneticPreview,
    sourceFile: "src/components/shomaui/effects/magnetic.tsx",
    registryName: "magnetic",
    dependencies: ["lodash"],
    code: `import Magnetic from "@/components/shomaui/effects/magnetic";\n\n<Magnetic><Button>Action</Button></Magnetic>`,
    sourceUrl: sourceLinks.triple,
    author: "ShomaUI + UI-TripleD references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "glow-hover-card",
    name: "Glow Hover Card",
    kind: "effects",
    category: "Hover",
    description: "Lift, border glow and shadow for card-level feedback.",
    tags: ["glow", "hover", "card"],
    preview: GlowCardPreview,
    sourceFile: "src/components/shomaui/effects/glow-hover-card.tsx",
    registryName: "glow-hover-card",
    dependencies: ["lodash"],
    code: `import GlowHoverCard from "@/components/shomaui/effects/glow-hover-card";\n\n<GlowHoverCard>...</GlowHoverCard>`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "marquee",
    name: "Marquee",
    kind: "animations",
    category: "Scroll",
    description: "Accessible looping content rail with reduced-motion support.",
    tags: ["marquee", "scroll", "css"],
    preview: MarqueePreview,
    sourceFile: "src/components/shomaui/animations/marquee.tsx",
    registryName: "marquee",
    dependencies: ["lodash"],
    code: `import Marquee from "@/components/shomaui/animations/marquee";\n\n<Marquee>{items}</Marquee>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "reveal",
    name: "Reveal",
    kind: "animations",
    category: "Scroll",
    description: "IntersectionObserver reveal primitive for progressive content.",
    tags: ["reveal", "scroll", "motion"],
    preview: RevealPreview,
    sourceFile: "src/components/shomaui/animations/reveal.tsx",
    registryName: "reveal",
    dependencies: ["lodash"],
    code: `import Reveal from "@/components/shomaui/animations/reveal";\n\n<Reveal>Content</Reveal>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "number-ticker",
    name: "Number Ticker",
    kind: "animations",
    category: "Numbers",
    description: "Smooth numeric counter for metrics and dashboard moments.",
    tags: ["number", "counter", "metrics"],
    preview: NumberTickerPreview,
    sourceFile: "src/components/shomaui/animations/number-ticker.tsx",
    registryName: "number-ticker",
    dependencies: ["lodash"],
    code: `import NumberTicker from "@/components/shomaui/animations/number-ticker";\n\n<NumberTicker value={12840} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "typing-text",
    name: "Typing Text",
    kind: "texts",
    category: "Reveal",
    description: "Looping typewriter text with live-region semantics.",
    tags: ["typing", "typewriter", "hero"],
    preview: TypingPreview,
    sourceFile: "src/components/shomaui/text/typing-text.tsx",
    registryName: "typing-text",
    dependencies: ["lodash"],
    code: `import TypingText from "@/components/shomaui/text/typing-text";\n\n<TypingText />`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shimmer-text",
    name: "Shimmer Text",
    kind: "texts",
    category: "Highlight",
    description: "Low-cost animated highlight sweep for headings and labels.",
    tags: ["shimmer", "shine", "css"],
    preview: ShimmerPreview,
    sourceFile: "src/components/shomaui/text/shimmer-text.tsx",
    registryName: "shimmer-text",
    dependencies: ["lodash"],
    code: `import ShimmerText from "@/components/shomaui/text/shimmer-text";\n\n<ShimmerText>ShomaUI in motion</ShimmerText>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "gradient-text",
    name: "Gradient Text",
    kind: "texts",
    category: "Color",
    description: "Token-aware gradient typography for expressive headlines.",
    tags: ["gradient", "typography", "css"],
    preview: GradientPreview,
    sourceFile: "src/components/shomaui/text/gradient-text.tsx",
    registryName: "gradient-text",
    dependencies: ["lodash"],
    code: `import GradientText from "@/components/shomaui/text/gradient-text";\n\n<GradientText>Make it memorable</GradientText>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
];

export const getCatalogProduct = (kind: CatalogKind) =>
  catalogProducts.find((product) => product.kind === kind) ?? catalogProducts[0];

export const getCatalogItems = (kind: CatalogKind) =>
  catalogItems.filter((item) => item.kind === kind);

export const getCatalogItem = (kind: CatalogKind, slug: string) =>
  catalogItems.find((item) => item.kind === kind && item.slug === slug);

export const catalogKindIcons = {
  components: Boxes,
  backgrounds: Eclipse,
  effects: Sparkles,
  animations: Activity,
  texts: AtSign,
  utility: Asterisk,
} as const;
