import type { ComponentType } from "react";
import {
  concat,
  filter,
  get,
  groupBy,
  kebabCase,
  keys,
  map,
  size,
  sortBy,
} from "lodash";
import {
  Activity,
  Asterisk,
  AtSign,
  Boxes,
  Component,
  Eclipse,
  Sparkles,
  TextCursorInput,
} from "lucide-react";

import {
  AvatarCatalogPreview,
  ActionMenuPreview,
  AnimatedListPreview,
  AuroraPreview,
  AuroraTextPreview,
  BlurFadePreview,
  BorderBeamPreview,
  BubblePreview,
  ButtonCatalogPreview,
  ConfettiPreview,
  CopyButtonPreview,
  DockPreview,
  DotPatternPreview,
  FileUploadPreview,
  FlickeringGridPreview,
  GlareHoverPreview,
  GradientBackgroundPreview,
  GlowCardPreview,
  GlassCardPreview,
  GradientPreview,
  HexagonPreview,
  ImageRevealPreview,
  GridPreview,
  InteractiveHoverButtonPreview,
  MagneticPreview,
  MarqueePreview,
  MeteorsPreview,
  MorphingTextPreview,
  NoisePreview,
  NumberTickerPreview,
  ProgressiveBlurPreview,
  RatingPreview,
  RainbowButtonPreview,
  RevealPreview,
  RetroGridPreview,
  RippleButtonPreview,
  ScrollProgressPreview,
  SegmentedControlPreview,
  ShineBorderPreview,
  ShimmerLoaderPreview,
  ShimmerPreview,
  ShinyButtonPreview,
  SparklesTextPreview,
  SpotlightPreview,
  StackingCardPreview,
  StarsPreview,
  StatusBadgePreview,
  TextHighlighterPreview,
  TextRevealPreview,
  TimelinePreview,
  TooltipCatalogPreview,
  TypingPreview,
  WordRotatePreview,
} from "./previews";
import { referenceCatalogItems } from "./reference-data";

export type CatalogKind =
  "components" | "backgrounds" | "effects" | "animations" | "texts";

export type CatalogProduct = {
  kind: CatalogKind;
  label: string;
  singularLabel: string;
  description: string;
  basePath: `/${CatalogKind}`;
  icon: typeof Component;
};

export type CatalogItem = {
  slug: string;
  name: string;
  kind: CatalogKind;
  category: string;
  description: string;
  tags: string[];
  preview: ComponentType;
  sourceFile: string;
  registryName: string;
  dependencies: string[];
  code: string;
  sourceUrl: string;
  author: string;
  license: string;
  attribution?: string;
};

export type CatalogCategory = {
  slug: string;
  label: string;
  count: number;
  href: `/${CatalogKind}`;
};

export const catalogProducts: CatalogProduct[] = [
  {
    kind: "components",
    label: "Components",
    singularLabel: "Component",
    description: "Accessible building blocks for product interfaces.",
    basePath: "/components",
    icon: Component,
  },
  {
    kind: "backgrounds",
    label: "Backgrounds",
    singularLabel: "Background",
    description: "Atmospheric surfaces for heroes, cards and sections.",
    basePath: "/backgrounds",
    icon: Eclipse,
  },
  {
    kind: "effects",
    label: "Effects",
    singularLabel: "Effect",
    description: "Focused hover, glow and pointer interactions.",
    basePath: "/effects",
    icon: Sparkles,
  },
  {
    kind: "animations",
    label: "Animations",
    singularLabel: "Animation",
    description: "Motion primitives that make interfaces feel alive.",
    basePath: "/animations",
    icon: Activity,
  },
  {
    kind: "texts",
    label: "Texts",
    singularLabel: "Text effect",
    description: "Expressive text treatments for product storytelling.",
    basePath: "/texts",
    icon: TextCursorInput,
  },
];

const sourceLinks = {
  magic: "https://magicui.design/docs/components",
  reui: "https://reui.io/components",
  layouts: "https://www.ui-layouts.com/components/buttons",
  triple: "https://ui.tripled.work/components",
  animate: "https://animate-ui.com/docs/components/backgrounds/stars",
  smooth: "https://smoothui.dev/docs/components/dropdown-menu",
} as const;

const baseDependencies = ["@base-ui/react", "lodash"];

const baseCatalogItems: CatalogItem[] = [
  {
    slug: "avatar",
    name: "Avatar",
    kind: "components",
    category: "Profiles",
    description:
      "Composable identity primitives for people, teams and presence.",
    tags: ["identity", "base-ui", "profile"],
    preview: AvatarCatalogPreview,
    sourceFile: "src/components/shomaui/avatar.tsx",
    registryName: "avatar",
    dependencies: baseDependencies,
    code: `import { Avatar, AvatarFallback } from "@/components/shomaui/avatar";\n\n<Avatar><AvatarFallback>SK</AvatarFallback></Avatar>`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "button",
    name: "Button",
    kind: "components",
    category: "Buttons",
    description: "Base UI powered actions with accessible states and sizes.",
    tags: ["actions", "base-ui", "forms"],
    preview: ButtonCatalogPreview,
    sourceFile: "src/components/shomaui/button.tsx",
    registryName: "button",
    dependencies: [...baseDependencies, "class-variance-authority"],
    code: `import { Button } from "@/components/shomaui/button";\n\n<Button>Continue</Button>`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    kind: "components",
    category: "Feedback",
    description:
      "Keyboard-friendly contextual help built on Base UI primitives.",
    tags: ["disclosure", "base-ui", "feedback"],
    preview: TooltipCatalogPreview,
    sourceFile: "src/components/shomaui/tooltip.tsx",
    registryName: "tooltip",
    dependencies: baseDependencies,
    code: `import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/shomaui/tooltip";\n\n<Tooltip>...</Tooltip>`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "action-menu",
    name: "Action Menu",
    kind: "components",
    category: "Navigation",
    description: "Compact actions menu with shortcuts and destructive states.",
    tags: ["menu", "dropdown", "base-ui"],
    preview: ActionMenuPreview,
    sourceFile: "src/components/shomaui/components/action-menu.tsx",
    registryName: "action-menu",
    dependencies: baseDependencies,
    code: `import { ActionMenu } from "@/components/shomaui/components/action-menu";\n\n<ActionMenu label="Actions" />`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "glass-card",
    name: "Glass Card",
    kind: "components",
    category: "Surfaces",
    description: "Layered glass surface for dashboards and product highlights.",
    tags: ["card", "glass", "surface"],
    preview: GlassCardPreview,
    sourceFile: "src/components/shomaui/components/glass-card.tsx",
    registryName: "glass-card",
    dependencies: ["lodash"],
    code: `import { GlassCard } from "@/components/shomaui/components/glass-card";\n\n<GlassCard glow>...</GlassCard>`,
    sourceUrl: sourceLinks.triple,
    author: "ShomaUI + UI-TripleD references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "status-badge",
    name: "Status Badge",
    kind: "components",
    category: "Feedback",
    description: "Consistent new, stable, beta and deprecated statuses.",
    tags: ["badge", "status", "feedback"],
    preview: StatusBadgePreview,
    sourceFile: "src/components/shomaui/components/status-badge.tsx",
    registryName: "status-badge",
    dependencies: ["@base-ui/react", "lodash"],
    code: `import { StatusBadge } from "@/components/shomaui/components/status-badge";\n\n<StatusBadge status="stable" />`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "segmented-control",
    name: "Segmented Control",
    kind: "components",
    category: "Navigation",
    description:
      "Base UI tab behavior presented as a compact segmented switcher.",
    tags: ["tabs", "navigation", "base-ui"],
    preview: SegmentedControlPreview,
    sourceFile: "src/components/shomaui/components/segmented-control.tsx",
    registryName: "segmented-control",
    dependencies: [...baseDependencies],
    code: `import { SegmentedControl } from "@/components/shomaui/components/segmented-control";\n\n<SegmentedControl items={["Day", "Week", "Month"]} />`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "rainbow-button",
    name: "Rainbow Button",
    kind: "components",
    category: "Buttons",
    description: "Animated gradient action button for high-emphasis moments.",
    tags: ["button", "gradient", "animated"],
    preview: RainbowButtonPreview,
    sourceFile: "src/components/shomaui/rainbow-button.tsx",
    registryName: "rainbow-button",
    dependencies: [...baseDependencies, "class-variance-authority"],
    code: `import RainbowButton from "@/components/shomaui/rainbow-button";\n\n<RainbowButton>Launch project</RainbowButton>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "ripple-button",
    name: "Ripple Button",
    kind: "components",
    category: "Buttons",
    description: "Click-position ripple feedback for tactile actions.",
    tags: ["button", "ripple", "interaction"],
    preview: RippleButtonPreview,
    sourceFile: "src/components/shomaui/ripple-button.tsx",
    registryName: "ripple-button",
    dependencies: ["lodash"],
    code: `import RippleButton from "@/components/shomaui/ripple-button";\n\n<RippleButton>Click me</RippleButton>`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shiny-button",
    name: "Shiny Button",
    kind: "components",
    category: "Buttons",
    description: "Motion-powered highlight sweep for premium calls to action.",
    tags: ["button", "motion", "shine"],
    preview: ShinyButtonPreview,
    sourceFile: "src/components/shomaui/shiny-button.tsx",
    registryName: "shiny-button",
    dependencies: ["lodash", "motion"],
    code: `import ShinyButton from "@/components/shomaui/shiny-button";\n\n<ShinyButton>Shiny action</ShinyButton>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "interactive-hover-button",
    name: "Interactive Hover Button",
    kind: "components",
    category: "Buttons",
    description: "Arrow-reveal button interaction for compact navigation.",
    tags: ["button", "hover", "navigation"],
    preview: InteractiveHoverButtonPreview,
    sourceFile: "src/components/shomaui/interactive-hover-button.tsx",
    registryName: "interactive-hover-button",
    dependencies: ["lodash", "lucide-react"],
    code: `import InteractiveHoverButton from "@/components/shomaui/interactive-hover-button";\n\n<InteractiveHoverButton>View details</InteractiveHoverButton>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "stars",
    name: "Stars Background",
    kind: "backgrounds",
    category: "Space",
    description: "Deterministic animated star field inspired by Animate UI.",
    tags: ["stars", "space", "animated"],
    preview: StarsPreview,
    sourceFile: "src/components/shomaui/background/stars-background.tsx",
    registryName: "stars-background",
    dependencies: ["lodash"],
    code: `import StarsBackground from "@/components/shomaui/background/stars-background";\n\n<StarsBackground>...</StarsBackground>`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
    attribution: "Inspired by the Animate UI Stars Background concept.",
  },
  {
    slug: "grid",
    name: "Grid Background",
    kind: "backgrounds",
    category: "Patterns",
    description: "Responsive CSS grid surface for structured layouts.",
    tags: ["grid", "pattern", "css"],
    preview: GridPreview,
    sourceFile: "src/components/shomaui/background/grid-background.tsx",
    registryName: "grid-background",
    dependencies: ["lodash"],
    code: `import GridBackground from "@/components/shomaui/background/grid-background";\n\n<GridBackground />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "aurora",
    name: "Aurora Background",
    kind: "backgrounds",
    category: "Gradients",
    description: "Soft layered gradient light for hero and empty states.",
    tags: ["aurora", "gradient", "hero"],
    preview: AuroraPreview,
    sourceFile: "src/components/shomaui/background/aurora-background.tsx",
    registryName: "aurora-background",
    dependencies: ["lodash"],
    code: `import AuroraBackground from "@/components/shomaui/background/aurora-background";\n\n<AuroraBackground>...</AuroraBackground>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "noise",
    name: "Noise Background",
    kind: "backgrounds",
    category: "Texture",
    description: "Asset-free texture layer made from CSS gradients.",
    tags: ["noise", "texture", "css"],
    preview: NoisePreview,
    sourceFile: "src/components/shomaui/background/noise-background.tsx",
    registryName: "noise-background",
    dependencies: ["lodash"],
    code: `import NoiseBackground from "@/components/shomaui/background/noise-background";\n\n<NoiseBackground />`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "spotlight-card",
    name: "Spotlight Card",
    kind: "effects",
    category: "Pointer",
    description: "Pointer-aware radial light that keeps content readable.",
    tags: ["spotlight", "pointer", "card"],
    preview: SpotlightPreview,
    sourceFile: "src/components/shomaui/effects/spotlight-card.tsx",
    registryName: "spotlight-card",
    dependencies: ["lodash"],
    code: `import SpotlightCard from "@/components/shomaui/effects/spotlight-card";\n\n<SpotlightCard>...</SpotlightCard>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shine-border",
    name: "Shine Border",
    kind: "effects",
    category: "Borders",
    description: "Lightweight conic-gradient border animation.",
    tags: ["border", "shine", "css"],
    preview: ShineBorderPreview,
    sourceFile: "src/components/shomaui/effects/shine-border.tsx",
    registryName: "shine-border",
    dependencies: ["lodash"],
    code: `import ShineBorder from "@/components/shomaui/effects/shine-border";\n\n<ShineBorder>...</ShineBorder>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "magnetic",
    name: "Magnetic",
    kind: "effects",
    category: "Pointer",
    description: "Subtle pointer attraction wrapper for interactive targets.",
    tags: ["magnetic", "pointer", "interaction"],
    preview: MagneticPreview,
    sourceFile: "src/components/shomaui/effects/magnetic.tsx",
    registryName: "magnetic",
    dependencies: ["lodash"],
    code: `import Magnetic from "@/components/shomaui/effects/magnetic";\n\n<Magnetic><Button>Action</Button></Magnetic>`,
    sourceUrl: sourceLinks.triple,
    author: "ShomaUI + UI-TripleD references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "glow-hover-card",
    name: "Glow Hover Card",
    kind: "effects",
    category: "Hover",
    description: "Lift, border glow and shadow for card-level feedback.",
    tags: ["glow", "hover", "card"],
    preview: GlowCardPreview,
    sourceFile: "src/components/shomaui/effects/glow-hover-card.tsx",
    registryName: "glow-hover-card",
    dependencies: ["lodash"],
    code: `import GlowHoverCard from "@/components/shomaui/effects/glow-hover-card";\n\n<GlowHoverCard>...</GlowHoverCard>`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "marquee",
    name: "Marquee",
    kind: "animations",
    category: "Scroll",
    description: "Accessible looping content rail with reduced-motion support.",
    tags: ["marquee", "scroll", "css"],
    preview: MarqueePreview,
    sourceFile: "src/components/shomaui/animations/marquee.tsx",
    registryName: "marquee",
    dependencies: ["lodash"],
    code: `import Marquee from "@/components/shomaui/animations/marquee";\n\n<Marquee>{items}</Marquee>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "reveal",
    name: "Reveal",
    kind: "animations",
    category: "Scroll",
    description:
      "IntersectionObserver reveal primitive for progressive content.",
    tags: ["reveal", "scroll", "motion"],
    preview: RevealPreview,
    sourceFile: "src/components/shomaui/animations/reveal.tsx",
    registryName: "reveal",
    dependencies: ["lodash"],
    code: `import Reveal from "@/components/shomaui/animations/reveal";\n\n<Reveal>Content</Reveal>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "number-ticker",
    name: "Number Ticker",
    kind: "animations",
    category: "Numbers",
    description: "Smooth numeric counter for metrics and dashboard moments.",
    tags: ["number", "counter", "metrics"],
    preview: NumberTickerPreview,
    sourceFile: "src/components/shomaui/animations/number-ticker.tsx",
    registryName: "number-ticker",
    dependencies: ["lodash"],
    code: `import NumberTicker from "@/components/shomaui/animations/number-ticker";\n\n<NumberTicker value={12840} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "typing-text",
    name: "Typing Text",
    kind: "texts",
    category: "Reveal",
    description: "Looping typewriter text with live-region semantics.",
    tags: ["typing", "typewriter", "hero"],
    preview: TypingPreview,
    sourceFile: "src/components/shomaui/text/typing-text.tsx",
    registryName: "typing-text",
    dependencies: ["lodash"],
    code: `import TypingText from "@/components/shomaui/text/typing-text";\n\n<TypingText />`,
    sourceUrl: sourceLinks.smooth,
    author: "ShomaUI + SmoothUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shimmer-text",
    name: "Shimmer Text",
    kind: "texts",
    category: "Highlight",
    description: "Low-cost animated highlight sweep for headings and labels.",
    tags: ["shimmer", "shine", "css"],
    preview: ShimmerPreview,
    sourceFile: "src/components/shomaui/text/shimmer-text.tsx",
    registryName: "shimmer-text",
    dependencies: ["lodash"],
    code: `import ShimmerText from "@/components/shomaui/text/shimmer-text";\n\n<ShimmerText>ShomaUI in motion</ShimmerText>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "gradient-text",
    name: "Gradient Text",
    kind: "texts",
    category: "Color",
    description: "Token-aware gradient typography for expressive headlines.",
    tags: ["gradient", "typography", "css"],
    preview: GradientPreview,
    sourceFile: "src/components/shomaui/text/gradient-text.tsx",
    registryName: "gradient-text",
    dependencies: ["lodash"],
    code: `import GradientText from "@/components/shomaui/text/gradient-text";\n\n<GradientText>Make it memorable</GradientText>`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "animated-list",
    name: "Animated List",
    kind: "components",
    category: "Content",
    description:
      "A compact live activity rail with gentle item emphasis and reduced visual noise.",
    tags: ["list", "activity", "motion"],
    preview: AnimatedListPreview,
    sourceFile: "src/components/shomaui/components/animated-list.tsx",
    registryName: "animated-list",
    dependencies: ["lodash"],
    code: `import AnimatedList from "@/components/shomaui/components/animated-list";\n\n<AnimatedList items={["Build completed", "Review ready"]} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
    attribution: "Inspired by the animated list pattern in Magic UI.",
  },
  {
    slug: "dock",
    name: "Dock",
    kind: "components",
    category: "Navigation",
    description:
      "A keyboard-friendly application dock with tooltip labels and active state.",
    tags: ["dock", "navigation", "tooltip"],
    preview: DockPreview,
    sourceFile: "src/components/shomaui/components/dock.tsx",
    registryName: "dock",
    dependencies: ["lodash"],
    code: `import Dock from "@/components/shomaui/components/dock";\n\n<Dock items={items} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "timeline",
    name: "Timeline",
    kind: "components",
    category: "Data",
    description:
      "A vertical milestone timeline for product progress, history and workflows.",
    tags: ["timeline", "milestones", "data"],
    preview: TimelinePreview,
    sourceFile: "src/components/shomaui/components/timeline.tsx",
    registryName: "timeline",
    dependencies: ["lodash", "lucide-react"],
    code: `import Timeline from "@/components/shomaui/components/timeline";\n\n<Timeline items={milestones} />`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "rating",
    name: "Rating",
    kind: "components",
    category: "Forms",
    description:
      "An accessible star rating input with keyboard and screen-reader labels.",
    tags: ["rating", "forms", "feedback"],
    preview: RatingPreview,
    sourceFile: "src/components/shomaui/components/rating.tsx",
    registryName: "rating",
    dependencies: ["lodash", "lucide-react"],
    code: `import Rating from "@/components/shomaui/components/rating";\n\n<Rating value={4} onValueChange={setRating} />`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "file-upload",
    name: "File Upload",
    kind: "components",
    category: "Forms",
    description:
      "Drag-and-drop file input with deduplication, selected-file list and remove actions.",
    tags: ["upload", "dropzone", "forms"],
    preview: FileUploadPreview,
    sourceFile: "src/components/shomaui/components/file-upload.tsx",
    registryName: "file-upload",
    dependencies: ["lodash", "lucide-react"],
    code: `import FileUpload from "@/components/shomaui/components/file-upload";\n\n<FileUpload accept="image/*" onFilesChange={setFiles} />`,
    sourceUrl: sourceLinks.reui,
    author: "ShomaUI + ReUI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "copy-button",
    name: "Copy Button",
    kind: "components",
    category: "Buttons",
    description:
      "A reusable clipboard action with a short-lived copied confirmation state.",
    tags: ["copy", "clipboard", "button"],
    preview: CopyButtonPreview,
    sourceFile: "src/components/shomaui/components/copy-button.tsx",
    registryName: "copy-button",
    dependencies: [
      ...baseDependencies,
      "class-variance-authority",
      "lucide-react",
    ],
    code: `import CopyButton from "@/components/shomaui/components/copy-button";\n\n<CopyButton value="npm install shomaui" />`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "flickering-grid",
    name: "Flickering Grid",
    kind: "backgrounds",
    category: "Patterns",
    description:
      "A deterministic grid of softly flickering cells for technical hero surfaces.",
    tags: ["grid", "flicker", "pattern"],
    preview: FlickeringGridPreview,
    sourceFile: "src/components/shomaui/background/flickering-grid.tsx",
    registryName: "flickering-grid",
    dependencies: ["lodash"],
    code: `import FlickeringGrid from "@/components/shomaui/background/flickering-grid";\n\n<FlickeringGrid>...</FlickeringGrid>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "retro-grid",
    name: "Retro Grid",
    kind: "backgrounds",
    category: "Patterns",
    description:
      "A perspective neon grid for launch pages, demos and atmospheric hero sections.",
    tags: ["retro", "grid", "hero"],
    preview: RetroGridPreview,
    sourceFile: "src/components/shomaui/background/retro-grid.tsx",
    registryName: "retro-grid",
    dependencies: ["lodash"],
    code: `import RetroGrid from "@/components/shomaui/background/retro-grid";\n\n<RetroGrid>...</RetroGrid>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "dot-pattern",
    name: "Dot Pattern",
    kind: "backgrounds",
    category: "Patterns",
    description:
      "A configurable CSS dot field with token-aware color, size and spacing.",
    tags: ["dots", "pattern", "css"],
    preview: DotPatternPreview,
    sourceFile: "src/components/shomaui/background/dot-pattern.tsx",
    registryName: "dot-pattern",
    dependencies: ["lodash"],
    code: `import DotPattern from "@/components/shomaui/background/dot-pattern";\n\n<DotPattern dotSize={2} gap={20} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "bubble-background",
    name: "Bubble Background",
    kind: "backgrounds",
    category: "Atmosphere",
    description:
      "A soft floating bubble field for playful empty states and onboarding moments.",
    tags: ["bubble", "ambient", "animated"],
    preview: BubblePreview,
    sourceFile: "src/components/shomaui/background/bubble-background.tsx",
    registryName: "bubble-background",
    dependencies: ["lodash"],
    code: `import BubbleBackground from "@/components/shomaui/background/bubble-background";\n\n<BubbleBackground>...</BubbleBackground>`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "gradient-background",
    name: "Gradient Background",
    kind: "backgrounds",
    category: "Gradients",
    description:
      "Layered radial gradients for soft focus without image assets.",
    tags: ["gradient", "hero", "css"],
    preview: GradientBackgroundPreview,
    sourceFile: "src/components/shomaui/background/gradient-background.tsx",
    registryName: "gradient-background",
    dependencies: ["lodash"],
    code: `import GradientBackground from "@/components/shomaui/background/gradient-background";\n\n<GradientBackground>...</GradientBackground>`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "hexagon-background",
    name: "Hexagon Background",
    kind: "backgrounds",
    category: "Patterns",
    description:
      "A lightweight hexagonal pattern for technical and infrastructure interfaces.",
    tags: ["hexagon", "pattern", "css"],
    preview: HexagonPreview,
    sourceFile: "src/components/shomaui/background/hexagon-background.tsx",
    registryName: "hexagon-background",
    dependencies: ["lodash"],
    code: `import HexagonBackground from "@/components/shomaui/background/hexagon-background";\n\n<HexagonBackground />`,
    sourceUrl: sourceLinks.animate,
    author: "ShomaUI + Animate UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "border-beam",
    name: "Border Beam",
    kind: "effects",
    category: "Borders",
    description:
      "A moving conic-gradient beam that draws attention to a card edge.",
    tags: ["beam", "border", "status"],
    preview: BorderBeamPreview,
    sourceFile: "src/components/shomaui/effects/border-beam.tsx",
    registryName: "border-beam",
    dependencies: ["lodash"],
    code: `import BorderBeam from "@/components/shomaui/effects/border-beam";\n\n<BorderBeam>...</BorderBeam>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "glare-hover",
    name: "Glare Hover",
    kind: "effects",
    category: "Hover",
    description:
      "Pointer-aware glare that adds depth while preserving readable content.",
    tags: ["glare", "hover", "pointer"],
    preview: GlareHoverPreview,
    sourceFile: "src/components/shomaui/effects/glare-hover.tsx",
    registryName: "glare-hover",
    dependencies: ["lodash"],
    code: `import GlareHover from "@/components/shomaui/effects/glare-hover";\n\n<GlareHover>...</GlareHover>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "meteors",
    name: "Meteors",
    kind: "effects",
    category: "Atmosphere",
    description: "A deterministic meteor shower for high-energy dark surfaces.",
    tags: ["meteors", "space", "ambient"],
    preview: MeteorsPreview,
    sourceFile: "src/components/shomaui/effects/meteors.tsx",
    registryName: "meteors",
    dependencies: ["lodash"],
    code: `import Meteors from "@/components/shomaui/effects/meteors";\n\n<Meteors count={12}>...</Meteors>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "confetti",
    name: "Confetti",
    kind: "effects",
    category: "Feedback",
    description:
      "A lightweight celebration burst for completion and release moments.",
    tags: ["confetti", "feedback", "celebration"],
    preview: ConfettiPreview,
    sourceFile: "src/components/shomaui/effects/confetti.tsx",
    registryName: "confetti",
    dependencies: [
      ...baseDependencies,
      "class-variance-authority",
      "lucide-react",
    ],
    code: `import Confetti from "@/components/shomaui/effects/confetti";\n\n<Confetti>Celebrate</Confetti>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "progressive-blur",
    name: "Progressive Blur",
    kind: "effects",
    category: "Surfaces",
    description:
      "A bottom or top blur veil that makes clipped content feel intentional.",
    tags: ["blur", "surface", "overflow"],
    preview: ProgressiveBlurPreview,
    sourceFile: "src/components/shomaui/effects/progressive-blur.tsx",
    registryName: "progressive-blur",
    dependencies: ["lodash"],
    code: `import ProgressiveBlur from "@/components/shomaui/effects/progressive-blur";\n\n<ProgressiveBlur>Long content</ProgressiveBlur>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "image-reveal",
    name: "Image Reveal",
    kind: "effects",
    category: "Media",
    description:
      "A focus-friendly image reveal that transitions from blur to clarity on hover.",
    tags: ["image", "reveal", "hover"],
    preview: ImageRevealPreview,
    sourceFile: "src/components/shomaui/effects/image-reveal.tsx",
    registryName: "image-reveal",
    dependencies: ["lodash"],
    code: `import ImageReveal from "@/components/shomaui/effects/image-reveal";\n\n<ImageReveal src="/cover.jpg" alt="Cover image" />`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "blur-fade",
    name: "Blur Fade",
    kind: "animations",
    category: "Reveal",
    description:
      "An IntersectionObserver-powered entrance animation with offset and delay controls.",
    tags: ["blur", "fade", "scroll"],
    preview: BlurFadePreview,
    sourceFile: "src/components/shomaui/animations/blur-fade.tsx",
    registryName: "blur-fade",
    dependencies: ["lodash"],
    code: `import BlurFade from "@/components/shomaui/animations/blur-fade";\n\n<BlurFade delay={120}>Content</BlurFade>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "stacking-card",
    name: "Stacking Card",
    kind: "animations",
    category: "Scroll",
    description:
      "Sticky cards that layer into a clear narrative as the page scrolls.",
    tags: ["stack", "sticky", "scroll"],
    preview: StackingCardPreview,
    sourceFile: "src/components/shomaui/animations/stacking-card.tsx",
    registryName: "stacking-card",
    dependencies: ["lodash"],
    code: `import StackingCard from "@/components/shomaui/animations/stacking-card";\n\n<StackingCard cards={cards} />`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "shimmer-loader",
    name: "Shimmer Loader",
    kind: "animations",
    category: "Loading",
    description:
      "A compact loading skeleton for text blocks and async content states.",
    tags: ["loader", "skeleton", "shimmer"],
    preview: ShimmerLoaderPreview,
    sourceFile: "src/components/shomaui/animations/shimmer-loader.tsx",
    registryName: "shimmer-loader",
    dependencies: ["lodash"],
    code: `import ShimmerLoader from "@/components/shomaui/animations/shimmer-loader";\n\n<ShimmerLoader lines={4} />`,
    sourceUrl: sourceLinks.layouts,
    author: "ShomaUI + UI Layouts references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "scroll-progress",
    name: "Scroll Progress",
    kind: "animations",
    category: "Scroll",
    description:
      "A fixed reading progress indicator that tracks the current document position.",
    tags: ["progress", "scroll", "reading"],
    preview: ScrollProgressPreview,
    sourceFile: "src/components/shomaui/animations/scroll-progress.tsx",
    registryName: "scroll-progress",
    dependencies: ["lodash"],
    code: `import ScrollProgress from "@/components/shomaui/animations/scroll-progress";\n\n<ScrollProgress />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "aurora-text",
    name: "Aurora Text",
    kind: "texts",
    category: "Color",
    description:
      "Animated aurora color movement for expressive headlines and labels.",
    tags: ["aurora", "gradient", "headline"],
    preview: AuroraTextPreview,
    sourceFile: "src/components/shomaui/text/aurora-text.tsx",
    registryName: "aurora-text",
    dependencies: ["lodash"],
    code: `import AuroraText from "@/components/shomaui/text/aurora-text";\n\n<AuroraText>Ship better</AuroraText>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "sparkles-text",
    name: "Sparkles Text",
    kind: "texts",
    category: "Highlight",
    description:
      "Small animated sparkles that make a short phrase feel special.",
    tags: ["sparkles", "highlight", "headline"],
    preview: SparklesTextPreview,
    sourceFile: "src/components/shomaui/text/sparkles-text.tsx",
    registryName: "sparkles-text",
    dependencies: ["lodash", "lucide-react"],
    code: `import SparklesText from "@/components/shomaui/text/sparkles-text";\n\n<SparklesText>New</SparklesText>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "morphing-text",
    name: "Morphing Text",
    kind: "texts",
    category: "Rotation",
    description:
      "Looping word changes for compact value propositions and hero copy.",
    tags: ["morph", "words", "hero"],
    preview: MorphingTextPreview,
    sourceFile: "src/components/shomaui/text/morphing-text.tsx",
    registryName: "morphing-text",
    dependencies: ["lodash"],
    code: `import MorphingText from "@/components/shomaui/text/morphing-text";\n\n<MorphingText words={["fast", "clear", "useful"]} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "text-reveal",
    name: "Text Reveal",
    kind: "texts",
    category: "Reveal",
    description:
      "A viewport-aware line reveal for editorial headings and section introductions.",
    tags: ["text", "reveal", "scroll"],
    preview: TextRevealPreview,
    sourceFile: "src/components/shomaui/text/text-reveal.tsx",
    registryName: "text-reveal",
    dependencies: ["lodash"],
    code: `import TextReveal from "@/components/shomaui/text/text-reveal";\n\n<TextReveal>Make the first impression count</TextReveal>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "text-highlighter",
    name: "Text Highlighter",
    kind: "texts",
    category: "Highlight",
    description:
      "A semantic inline highlight that turns product copy into a visual cue.",
    tags: ["highlight", "inline", "copy"],
    preview: TextHighlighterPreview,
    sourceFile: "src/components/shomaui/text/text-highlighter.tsx",
    registryName: "text-highlighter",
    dependencies: ["lodash"],
    code: `import TextHighlighter from "@/components/shomaui/text/text-highlighter";\n\n<TextHighlighter>important</TextHighlighter>`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
  {
    slug: "word-rotate",
    name: "Word Rotate",
    kind: "texts",
    category: "Rotation",
    description:
      "An accessible rotating word primitive for concise animated copy.",
    tags: ["rotate", "words", "motion"],
    preview: WordRotatePreview,
    sourceFile: "src/components/shomaui/text/word-rotate.tsx",
    registryName: "word-rotate",
    dependencies: ["lodash"],
    code: `import WordRotate from "@/components/shomaui/text/word-rotate";\n\n<WordRotate words={["design", "build", "ship"]} />`,
    sourceUrl: sourceLinks.magic,
    author: "ShomaUI + Magic UI references",
    license: "MIT-compatible adaptation",
  },
];

export const catalogItems: CatalogItem[] = concat(
  baseCatalogItems,
  referenceCatalogItems,
);

export const getCatalogProduct = (kind: CatalogKind) =>
  catalogProducts.find((product) => product.kind === kind) ??
  catalogProducts[0];

export const getCatalogItems = (kind: CatalogKind) =>
  filter(catalogItems, (item) => item.kind === kind);

export const getCatalogCategories = (kind: CatalogKind): CatalogCategory[] => {
  const product = getCatalogProduct(kind);
  const items = getCatalogItems(kind);
  const groupedItems = groupBy(items, "category");

  return concat(
    [
      {
        slug: "all",
        label: `All ${product.label}`,
        count: size(items),
        href: product.basePath,
      },
    ],
    map(sortBy(keys(groupedItems)), (label) => ({
      slug: kebabCase(label),
      label,
      count: size(get(groupedItems, label, [])),
      href: product.basePath,
    })),
  );
};

export const getCatalogItem = (kind: CatalogKind, slug: string) =>
  get(
    filter(catalogItems, (item) => item.kind === kind && item.slug === slug),
    0,
  );

export const catalogKindIcons = {
  components: Boxes,
  backgrounds: Eclipse,
  effects: Sparkles,
  animations: Activity,
  texts: AtSign,
  utility: Asterisk,
} as const;
