/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentSkillsRouteImport } from './routes/agent-skills'
import { Route as AllAccessRouteImport } from './routes/all-access'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FigmaRouteImport } from './routes/figma'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as McpServerRouteImport } from './routes/mcp-server'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AnimationsIndexRouteImport } from './routes/animations/index'
import { Route as AnimationsSlugRouteImport } from './routes/animations/$slug'
import { Route as BackgroundsIndexRouteImport } from './routes/backgrounds/index'
import { Route as BackgroundsSlugRouteImport } from './routes/backgrounds/$slug'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsSlugRouteImport } from './routes/components/$slug'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'
import { Route as ComponentsAlertDialogRouteImport } from './routes/components/alert-dialog'
import { Route as ComponentsAspectRatioRouteImport } from './routes/components/aspect-ratio'
import { Route as ComponentsAutocompleteRouteImport } from './routes/components/autocomplete'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsBreadcrumbRouteImport } from './routes/components/breadcrumb'
import { Route as ComponentsButtonGroupRouteImport } from './routes/components/button-group'
import { Route as ComponentsCalendarRouteImport } from './routes/components/calendar'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsCarouselRouteImport } from './routes/components/carousel'
import { Route as ComponentsCascaderRouteImport } from './routes/components/cascader'
import { Route as ComponentsChartRouteImport } from './routes/components/chart'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsCodeBlockRouteImport } from './routes/components/code-block'
import { Route as ComponentsCollapsibleRouteImport } from './routes/components/collapsible'
import { Route as ComponentsComboboxRouteImport } from './routes/components/combobox'
import { Route as ComponentsCommandRouteImport } from './routes/components/command'
import { Route as ComponentsContextMenuRouteImport } from './routes/components/context-menu'
import { Route as ComponentsDataGridRouteImport } from './routes/components/data-grid'
import { Route as EffectsIndexRouteImport } from './routes/effects/index'
import { Route as EffectsSlugRouteImport } from './routes/effects/$slug'
import { Route as TextsIndexRouteImport } from './routes/texts/index'
import { Route as TextsSlugRouteImport } from './routes/texts/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/agent-skills',
  path: '/agent-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AllAccessRoute = AllAccessRouteImport.update({
  id: '/all-access',
  path: '/all-access',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FigmaRoute = FigmaRouteImport.update({
  id: '/figma',
  path: '/figma',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const McpServerRoute = McpServerRouteImport.update({
  id: '/mcp-server',
  path: '/mcp-server',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsIndexRoute = AnimationsIndexRouteImport.update({
  id: '/animations/',
  path: '/animations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsSlugRoute = AnimationsSlugRouteImport.update({
  id: '/animations/$slug',
  path: '/animations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundsIndexRoute = BackgroundsIndexRouteImport.update({
  id: '/backgrounds/',
  path: '/backgrounds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundsSlugRoute = BackgroundsSlugRouteImport.update({
  id: '/backgrounds/$slug',
  path: '/backgrounds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/components/alert',
  path: '/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertDialogRoute = ComponentsAlertDialogRouteImport.update({
  id: '/components/alert-dialog',
  path: '/components/alert-dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAspectRatioRoute = ComponentsAspectRatioRouteImport.update({
  id: '/components/aspect-ratio',
  path: '/components/aspect-ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAutocompleteRoute = ComponentsAutocompleteRouteImport.update({
  id: '/components/autocomplete',
  path: '/components/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBreadcrumbRoute = ComponentsBreadcrumbRouteImport.update({
  id: '/components/breadcrumb',
  path: '/components/breadcrumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonGroupRoute = ComponentsButtonGroupRouteImport.update({
  id: '/components/button-group',
  path: '/components/button-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCalendarRoute = ComponentsCalendarRouteImport.update({
  id: '/components/calendar',
  path: '/components/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCarouselRoute = ComponentsCarouselRouteImport.update({
  id: '/components/carousel',
  path: '/components/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCascaderRoute = ComponentsCascaderRouteImport.update({
  id: '/components/cascader',
  path: '/components/cascader',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChartRoute = ComponentsChartRouteImport.update({
  id: '/components/chart',
  path: '/components/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCodeBlockRoute = ComponentsCodeBlockRouteImport.update({
  id: '/components/code-block',
  path: '/components/code-block',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCollapsibleRoute = ComponentsCollapsibleRouteImport.update({
  id: '/components/collapsible',
  path: '/components/collapsible',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComboboxRoute = ComponentsComboboxRouteImport.update({
  id: '/components/combobox',
  path: '/components/combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCommandRoute = ComponentsCommandRouteImport.update({
  id: '/components/command',
  path: '/components/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsContextMenuRoute = ComponentsContextMenuRouteImport.update({
  id: '/components/context-menu',
  path: '/components/context-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataGridRoute = ComponentsDataGridRouteImport.update({
  id: '/components/data-grid',
  path: '/components/data-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectsIndexRoute = EffectsIndexRouteImport.update({
  id: '/effects/',
  path: '/effects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectsSlugRoute = EffectsSlugRouteImport.update({
  id: '/effects/$slug',
  path: '/effects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TextsIndexRoute = TextsIndexRouteImport.update({
  id: '/texts/',
  path: '/texts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextsSlugRoute = TextsSlugRouteImport.update({
  id: '/texts/$slug',
  path: '/texts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-skills': typeof AgentSkillsRoute
  '/all-access': typeof AllAccessRoute
  '/blocks': typeof BlocksRoute
  '/docs': typeof DocsRoute
  '/figma': typeof FigmaRoute
  '/icons': typeof IconsRoute
  '/mcp-server': typeof McpServerRoute
  '/pricing': typeof PricingRoute
  '/roadmap': typeof RoadmapRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRoute
  '/animations/$slug': typeof AnimationsSlugRoute
  '/backgrounds/$slug': typeof BackgroundsSlugRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/autocomplete': typeof ComponentsAutocompleteRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button-group': typeof ComponentsButtonGroupRoute
  '/components/calendar': typeof ComponentsCalendarRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/cascader': typeof ComponentsCascaderRoute
  '/components/chart': typeof ComponentsChartRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/code-block': typeof ComponentsCodeBlockRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/data-grid': typeof ComponentsDataGridRoute
  '/effects/$slug': typeof EffectsSlugRoute
  '/texts/$slug': typeof TextsSlugRoute
  '/animations/': typeof AnimationsIndexRoute
  '/backgrounds/': typeof BackgroundsIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/effects/': typeof EffectsIndexRoute
  '/texts/': typeof TextsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-skills': typeof AgentSkillsRoute
  '/all-access': typeof AllAccessRoute
  '/blocks': typeof BlocksRoute
  '/docs': typeof DocsRoute
  '/figma': typeof FigmaRoute
  '/icons': typeof IconsRoute
  '/mcp-server': typeof McpServerRoute
  '/pricing': typeof PricingRoute
  '/roadmap': typeof RoadmapRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRoute
  '/animations/$slug': typeof AnimationsSlugRoute
  '/backgrounds/$slug': typeof BackgroundsSlugRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/autocomplete': typeof ComponentsAutocompleteRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button-group': typeof ComponentsButtonGroupRoute
  '/components/calendar': typeof ComponentsCalendarRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/cascader': typeof ComponentsCascaderRoute
  '/components/chart': typeof ComponentsChartRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/code-block': typeof ComponentsCodeBlockRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/data-grid': typeof ComponentsDataGridRoute
  '/effects/$slug': typeof EffectsSlugRoute
  '/texts/$slug': typeof TextsSlugRoute
  '/animations': typeof AnimationsIndexRoute
  '/backgrounds': typeof BackgroundsIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/effects': typeof EffectsIndexRoute
  '/texts': typeof TextsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-skills': typeof AgentSkillsRoute
  '/all-access': typeof AllAccessRoute
  '/blocks': typeof BlocksRoute
  '/docs': typeof DocsRoute
  '/figma': typeof FigmaRoute
  '/icons': typeof IconsRoute
  '/mcp-server': typeof McpServerRoute
  '/pricing': typeof PricingRoute
  '/roadmap': typeof RoadmapRoute
  '/support': typeof SupportRoute
  '/templates': typeof TemplatesRoute
  '/animations/$slug': typeof AnimationsSlugRoute
  '/backgrounds/$slug': typeof BackgroundsSlugRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/aspect-ratio': typeof ComponentsAspectRatioRoute
  '/components/autocomplete': typeof ComponentsAutocompleteRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button-group': typeof ComponentsButtonGroupRoute
  '/components/calendar': typeof ComponentsCalendarRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/carousel': typeof ComponentsCarouselRoute
  '/components/cascader': typeof ComponentsCascaderRoute
  '/components/chart': typeof ComponentsChartRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/code-block': typeof ComponentsCodeBlockRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/data-grid': typeof ComponentsDataGridRoute
  '/effects/$slug': typeof EffectsSlugRoute
  '/texts/$slug': typeof TextsSlugRoute
  '/animations/': typeof AnimationsIndexRoute
  '/backgrounds/': typeof BackgroundsIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/effects/': typeof EffectsIndexRoute
  '/texts/': typeof TextsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-skills'
    | '/all-access'
    | '/blocks'
    | '/docs'
    | '/figma'
    | '/icons'
    | '/mcp-server'
    | '/pricing'
    | '/roadmap'
    | '/support'
    | '/templates'
    | '/animations/$slug'
    | '/backgrounds/$slug'
    | '/components/$slug'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/aspect-ratio'
    | '/components/autocomplete'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button-group'
    | '/components/calendar'
    | '/components/card'
    | '/components/carousel'
    | '/components/cascader'
    | '/components/chart'
    | '/components/checkbox'
    | '/components/code-block'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/command'
    | '/components/context-menu'
    | '/components/data-grid'
    | '/effects/$slug'
    | '/texts/$slug'
    | '/animations/'
    | '/backgrounds/'
    | '/components/'
    | '/effects/'
    | '/texts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-skills'
    | '/all-access'
    | '/blocks'
    | '/docs'
    | '/figma'
    | '/icons'
    | '/mcp-server'
    | '/pricing'
    | '/roadmap'
    | '/support'
    | '/templates'
    | '/animations/$slug'
    | '/backgrounds/$slug'
    | '/components/$slug'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/aspect-ratio'
    | '/components/autocomplete'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button-group'
    | '/components/calendar'
    | '/components/card'
    | '/components/carousel'
    | '/components/cascader'
    | '/components/chart'
    | '/components/checkbox'
    | '/components/code-block'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/command'
    | '/components/context-menu'
    | '/components/data-grid'
    | '/effects/$slug'
    | '/texts/$slug'
    | '/animations'
    | '/backgrounds'
    | '/components'
    | '/effects'
    | '/texts'
  id:
    | '__root__'
    | '/'
    | '/agent-skills'
    | '/all-access'
    | '/blocks'
    | '/docs'
    | '/figma'
    | '/icons'
    | '/mcp-server'
    | '/pricing'
    | '/roadmap'
    | '/support'
    | '/templates'
    | '/animations/$slug'
    | '/backgrounds/$slug'
    | '/components/$slug'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/aspect-ratio'
    | '/components/autocomplete'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button-group'
    | '/components/calendar'
    | '/components/card'
    | '/components/carousel'
    | '/components/cascader'
    | '/components/chart'
    | '/components/checkbox'
    | '/components/code-block'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/command'
    | '/components/context-menu'
    | '/components/data-grid'
    | '/effects/$slug'
    | '/texts/$slug'
    | '/animations/'
    | '/backgrounds/'
    | '/components/'
    | '/effects/'
    | '/texts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AllAccessRoute: typeof AllAccessRoute
  BlocksRoute: typeof BlocksRoute
  DocsRoute: typeof DocsRoute
  FigmaRoute: typeof FigmaRoute
  IconsRoute: typeof IconsRoute
  McpServerRoute: typeof McpServerRoute
  PricingRoute: typeof PricingRoute
  RoadmapRoute: typeof RoadmapRoute
  SupportRoute: typeof SupportRoute
  TemplatesRoute: typeof TemplatesRoute
  AnimationsSlugRoute: typeof AnimationsSlugRoute
  BackgroundsSlugRoute: typeof BackgroundsSlugRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAlertDialogRoute: typeof ComponentsAlertDialogRoute
  ComponentsAspectRatioRoute: typeof ComponentsAspectRatioRoute
  ComponentsAutocompleteRoute: typeof ComponentsAutocompleteRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsBreadcrumbRoute: typeof ComponentsBreadcrumbRoute
  ComponentsButtonGroupRoute: typeof ComponentsButtonGroupRoute
  ComponentsCalendarRoute: typeof ComponentsCalendarRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsCarouselRoute: typeof ComponentsCarouselRoute
  ComponentsCascaderRoute: typeof ComponentsCascaderRoute
  ComponentsChartRoute: typeof ComponentsChartRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsCodeBlockRoute: typeof ComponentsCodeBlockRoute
  ComponentsCollapsibleRoute: typeof ComponentsCollapsibleRoute
  ComponentsComboboxRoute: typeof ComponentsComboboxRoute
  ComponentsCommandRoute: typeof ComponentsCommandRoute
  ComponentsContextMenuRoute: typeof ComponentsContextMenuRoute
  ComponentsDataGridRoute: typeof ComponentsDataGridRoute
  EffectsSlugRoute: typeof EffectsSlugRoute
  TextsSlugRoute: typeof TextsSlugRoute
  AnimationsIndexRoute: typeof AnimationsIndexRoute
  BackgroundsIndexRoute: typeof BackgroundsIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  EffectsIndexRoute: typeof EffectsIndexRoute
  TextsIndexRoute: typeof TextsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-skills': {
      id: '/agent-skills'
      path: '/agent-skills'
      fullPath: '/agent-skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-access': {
      id: '/all-access'
      path: '/all-access'
      fullPath: '/all-access'
      preLoaderRoute: typeof AllAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figma': {
      id: '/figma'
      path: '/figma'
      fullPath: '/figma'
      preLoaderRoute: typeof FigmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-server': {
      id: '/mcp-server'
      path: '/mcp-server'
      fullPath: '/mcp-server'
      preLoaderRoute: typeof McpServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations/': {
      id: '/animations/'
      path: '/animations'
      fullPath: '/animations/'
      preLoaderRoute: typeof AnimationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations/$slug': {
      id: '/animations/$slug'
      path: '/animations/$slug'
      fullPath: '/animations/$slug'
      preLoaderRoute: typeof AnimationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgrounds/': {
      id: '/backgrounds/'
      path: '/backgrounds'
      fullPath: '/backgrounds/'
      preLoaderRoute: typeof BackgroundsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backgrounds/$slug': {
      id: '/backgrounds/$slug'
      path: '/backgrounds/$slug'
      fullPath: '/backgrounds/$slug'
      preLoaderRoute: typeof BackgroundsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/components/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/components/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert-dialog': {
      id: '/components/alert-dialog'
      path: '/components/alert-dialog'
      fullPath: '/components/alert-dialog'
      preLoaderRoute: typeof ComponentsAlertDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/aspect-ratio': {
      id: '/components/aspect-ratio'
      path: '/components/aspect-ratio'
      fullPath: '/components/aspect-ratio'
      preLoaderRoute: typeof ComponentsAspectRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/autocomplete': {
      id: '/components/autocomplete'
      path: '/components/autocomplete'
      fullPath: '/components/autocomplete'
      preLoaderRoute: typeof ComponentsAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/breadcrumb': {
      id: '/components/breadcrumb'
      path: '/components/breadcrumb'
      fullPath: '/components/breadcrumb'
      preLoaderRoute: typeof ComponentsBreadcrumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button-group': {
      id: '/components/button-group'
      path: '/components/button-group'
      fullPath: '/components/button-group'
      preLoaderRoute: typeof ComponentsButtonGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/calendar': {
      id: '/components/calendar'
      path: '/components/calendar'
      fullPath: '/components/calendar'
      preLoaderRoute: typeof ComponentsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card': {
      id: '/components/card'
      path: '/components/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/carousel': {
      id: '/components/carousel'
      path: '/components/carousel'
      fullPath: '/components/carousel'
      preLoaderRoute: typeof ComponentsCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/cascader': {
      id: '/components/cascader'
      path: '/components/cascader'
      fullPath: '/components/cascader'
      preLoaderRoute: typeof ComponentsCascaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chart': {
      id: '/components/chart'
      path: '/components/chart'
      fullPath: '/components/chart'
      preLoaderRoute: typeof ComponentsChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/code-block': {
      id: '/components/code-block'
      path: '/components/code-block'
      fullPath: '/components/code-block'
      preLoaderRoute: typeof ComponentsCodeBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/collapsible': {
      id: '/components/collapsible'
      path: '/components/collapsible'
      fullPath: '/components/collapsible'
      preLoaderRoute: typeof ComponentsCollapsibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/combobox': {
      id: '/components/combobox'
      path: '/components/combobox'
      fullPath: '/components/combobox'
      preLoaderRoute: typeof ComponentsComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/command': {
      id: '/components/command'
      path: '/components/command'
      fullPath: '/components/command'
      preLoaderRoute: typeof ComponentsCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/context-menu': {
      id: '/components/context-menu'
      path: '/components/context-menu'
      fullPath: '/components/context-menu'
      preLoaderRoute: typeof ComponentsContextMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-grid': {
      id: '/components/data-grid'
      path: '/components/data-grid'
      fullPath: '/components/data-grid'
      preLoaderRoute: typeof ComponentsDataGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effects/': {
      id: '/effects/'
      path: '/effects'
      fullPath: '/effects/'
      preLoaderRoute: typeof EffectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effects/$slug': {
      id: '/effects/$slug'
      path: '/effects/$slug'
      fullPath: '/effects/$slug'
      preLoaderRoute: typeof EffectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texts/': {
      id: '/texts/'
      path: '/texts'
      fullPath: '/texts/'
      preLoaderRoute: typeof TextsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/texts/$slug': {
      id: '/texts/$slug'
      path: '/texts/$slug'
      fullPath: '/texts/$slug'
      preLoaderRoute: typeof TextsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AllAccessRoute: AllAccessRoute,
  BlocksRoute: BlocksRoute,
  DocsRoute: DocsRoute,
  FigmaRoute: FigmaRoute,
  IconsRoute: IconsRoute,
  McpServerRoute: McpServerRoute,
  PricingRoute: PricingRoute,
  RoadmapRoute: RoadmapRoute,
  SupportRoute: SupportRoute,
  TemplatesRoute: TemplatesRoute,
  AnimationsSlugRoute: AnimationsSlugRoute,
  BackgroundsSlugRoute: BackgroundsSlugRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAlertDialogRoute: ComponentsAlertDialogRoute,
  ComponentsAspectRatioRoute: ComponentsAspectRatioRoute,
  ComponentsAutocompleteRoute: ComponentsAutocompleteRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsBreadcrumbRoute: ComponentsBreadcrumbRoute,
  ComponentsButtonGroupRoute: ComponentsButtonGroupRoute,
  ComponentsCalendarRoute: ComponentsCalendarRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsCarouselRoute: ComponentsCarouselRoute,
  ComponentsCascaderRoute: ComponentsCascaderRoute,
  ComponentsChartRoute: ComponentsChartRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsCodeBlockRoute: ComponentsCodeBlockRoute,
  ComponentsCollapsibleRoute: ComponentsCollapsibleRoute,
  ComponentsComboboxRoute: ComponentsComboboxRoute,
  ComponentsCommandRoute: ComponentsCommandRoute,
  ComponentsContextMenuRoute: ComponentsContextMenuRoute,
  ComponentsDataGridRoute: ComponentsDataGridRoute,
  EffectsSlugRoute: EffectsSlugRoute,
  TextsSlugRoute: TextsSlugRoute,
  AnimationsIndexRoute: AnimationsIndexRoute,
  BackgroundsIndexRoute: BackgroundsIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  EffectsIndexRoute: EffectsIndexRoute,
  TextsIndexRoute: TextsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
